### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by talentlessguy** [bondarevts/mltran#2]
When running a CLI I get this error:

```
❯ mltran exposure
Traceback (most recent call last):
  File "/home/v1rtl/.local/bin/mltran", line 281, in <module>
    main()
  File "/home/v1rtl/.local/bin/mltran", line 270, in main
    word = word.decode('utf8').encode('cp1251')
AttributeError: 'str' object has no attribute 'decode'
```

I have python (python2), python3 and python3.7 installed globally. which version does this CLI use?

**Comment by bondarevts** [comment]
It was written for Python 2. Since then, multitran.com has changed a lot. Let me see if I can fix this and make it compatible with Python 3.

**Comment by bondarevts** [comment]
Should work now. It will still be rather unstable until I figure out all the changes in the website layout.
